CONDA_BUILD_SYSROOT:
  - /opt/MacOSX10.15.sdk [osx]

python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
  - 3.10

cxx_compiler:
  - vs2019                     # [win]

c_compiler:
  - vs2019                     # [win]